[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
via_ir = true
optimizer_runs = 200
gas_reports = ["*"]
solc_version = "0.8.28"
fs_permissions = [{ access = "read-write", path = "../" }]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
sepolia = "https://endpoints.omniatech.io/v1/eth/sepolia/public"

[etherscan]
sepolia = { key = "${SEPOLIA_ETHERSCAN_API_KEY}", chain = 11155111 }
