[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
via_ir = true
optimizer_runs = 200
gas_reports = ["*"]
solc_version = "0.8.28"
fs_permissions = [{ access = "read-write", path = "../" }]